### PR TITLE
Stop continuous scrolling

### LINKED ISSUE #8: stop continuous scrolling
I am using android panoramaGL,it is working fine 360 sphere and sensor rotation. But when you click on image and scroll some distance with out lifting fingure on screen, it is scrolling continuously(my fingure is not moving but it is scrolling)how to stop it...

### PR DESCRIPTION
**Pull request by grammesm**
- Allow PLManager to be configured to disable the accelerated touch scrolling behavior.

### CODE REVIEW

**Comment by grammesm** [comment]
@hannesa2  I've never submitted a pull request on public github before.. not sure if there's anything I need to do

**Comment by hannesa2** [comment]
close #8

**Comment by hannesa2** [comment]
Sorry for the delay. First of all thank you for your contribution.

Before I merge, I tried to reproduce the miss function. 
First, I use current master and I observed no miss function.

Second, I switched on acceleration
`isAccelerometerEnabled = true`
and I observed I observed no miss function.

Please tell me, what I've to do, to see it

**Comment by grammesm** [comment]
No worries - sorry for the language barrier, but when you say "miss function" are you referring to what is currently wrong in the master branch?

This doesn't have to do with the accelerometer, but when you move the map with your fingers.

In the master branch - if you touch the map and drag, you can see as you get further away from the original touch point as you are dragging, the map moves and rotates faster and faster.  In my pull request, if you look at `MainActivity.kt` - I set the NEW flag `isAcceleratedTouchScrollingEnabled` to false. After increasing the rotational sensitivity of the panorama's camera to 270, now if you try and move the map with your finger it will only move when  your finger is moving, rather than all the time until you lift your finger.

Hope this explanation helps?

Matt

**Pull request merged**
